<?php
$labels = array();
$labels['export_provisioning'] = 'Provisionierung';
$labels['pagetitle'] = 'Exportiere E-Mail-Provisierungs-Profil';
$labels['boxtitle'] = 'Exportiere E-Mail-Provisierungs-Profil';
$labels['apple'] = 'Apple';
$labels['microsoft'] = 'Microsoft';
$labels['download_ios'] = 'Lade Profil (Konfiguration) für iOS / OSX herunter';
$labels['download_iaf'] = 'Lade Profil (Konfiguration) für Outlook Express / Windows Live Mail herunter';
$labels['PayloadDescription'] = 'E-Mail-Account-Einstellungen'; // description inside configuration profile
$labels['download'] = 'Download';
$labels['identity'] = 'Identität';
$labels['identity_label'] = 'Wähle die zu exportierende Identität';
?>
