<?php

$labels = array();
$labels['export_provisioning'] = 'Provisioning';
$labels['pagetitle'] = 'Export email provisioning profile';
$labels['boxtitle'] = 'Export email provisioning profile';
$labels['apple'] = 'Apple';
$labels['microsoft'] = 'Microsoft';
$labels['download_ios'] = 'Download provisioning (configuration) profile for iOS / OSX';
$labels['download_iaf'] = 'Download provisioning (configuration) profile for Outlook Express / Windows Live Mail';
$labels['PayloadDescription'] = 'email account settings'; // description inside configuration profile
$labels['download'] = 'Download';
$labels['identity'] = 'Identity';
$labels['identity_label'] = 'Choose the identity to export';



?>
