<?php

$labels = array();
$labels['export_provisioning'] = 'Konfigurációs Profil';
$labels['pagetitle'] = 'Email konfigurációs profil Exportálás';
$labels['boxtitle'] = 'Email konfigurációs profil Exportálás';
$labels['apple'] = 'Apple';
$labels['microsoft'] = 'Microsoft';
$labels['download_ios'] = 'iOS / OSX konfigurációs profil';
$labels['download_iaf'] = 'Outlook Express / Windows Live Mail konfigurációs profil';
$labels['PayloadDescription'] = 'Email fiók beállítás'; // description inside configuration profile
$labels['identity'] = 'Azonosító';



?>
