<?php

$labels = array();
$labels['export_provisioning'] = 'Profilo di configurazione';
$labels['pagetitle'] = 'Esporta profilo di configurazione email';
$labels['boxtitle'] = 'Esporta profilo di configurazione email';
$labels['apple'] = 'Apple';
$labels['microsoft'] = 'Microsoft';
$labels['download_ios'] = 'Download provisioning (configuration) profile for iOS / OSX';
$labels['download_iaf'] = 'Download provisioning (configuration) profile for Outlook / Outlook Express / Windows Live Mail';
$labels['PayloadDescription'] = 'Impostazioni account email'; // description inside configuration profile
$labels['download'] = 'Download';




?>
