<?php

$labels = array();
$labels['export_provisioning'] = 'Configuratieprofiel exporteren';
$labels['pagetitle'] = 'Exporteer e-mail configuratieprofiel';
$labels['boxtitle'] = 'Exporteer e-mail configuratieprofiel';
$labels['apple'] = 'Apple';
$labels['microsoft'] = 'Microsoft';
$labels['download_ios'] = 'Download configuratieprofiel voor iOS / OSX';
$labels['download_iaf'] = 'Download configuratieprofiel voor Outlook Express / Windows Live Mail';
$labels['PayloadDescription'] = 'email account instellingen'; // description inside configuration profile
$labels['download'] = 'Downloaden';
$labels['identity'] = 'Identiteit';
$labels['identity_label'] = 'Kies een identiteit om te exporteren';



?>
